import 'package:flutter/material.dart';

class LegalDocumentSection {
  const LegalDocumentSection(this.heading, this.text);

  final String heading;
  final String text;
}

class LegalDocument {
  const LegalDocument({required this.title, required this.sections});

  final String title;
  final List<LegalDocumentSection> sections;
}

class LegalDocuments {
  static const terms = LegalDocument(
    title: 'End-User License Agreement and Terms of Service',
    sections: [
      LegalDocumentSection(
        'APEX TACTICAL PERFORMANCE',
        'Effective Date: 15 September 2026\nLast Updated: 15 September 2026\n\nPLEASE READ THIS END-USER LICENSE AGREEMENT AND TERMS OF SERVICE (THE "AGREEMENT") CAREFULLY BEFORE DOWNLOADING, SUBSCRIBING TO, OR USING APEX TACTICAL PERFORMANCE (THE "APP").\n\nTHIS AGREEMENT CONTAINS A DISCLAIMER OF WARRANTIES, A RELEASE OF LIABILITY, AN ASSUMPTION OF RISK, AND A BINDING ARBITRATION/CLASS ACTION WAIVER PROVISION. BY ACCESSING, DOWNLOADING, PAYING FOR, OR USING THE APP, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND UNEQUIVOCALLY AGREE TO BE BOUND BY ALL OF THE TERMS BELOW. IF YOU DO NOT AGREE, DO NOT DOWNLOAD, SUBSCRIBE TO, OR USE THE APP.',
      ),
      LegalDocumentSection(
        '1. Nature of the Service & Artificial Intelligence Disclaimer',
        '1.1 AI-Generated Content\nYou explicitly understand, acknowledge, and agree that APEX TACTICAL PERFORMANCE is an artificial intelligence-driven application. All fitness plans, workout routines, nutritional advice, tactical performance coaching, medical guidance, injury prevention tips, mental performance strategies, and any other responses provided through the App are generated by an artificial intelligence (AI) model.\n\n1.2 Inherent AI Limitations and Potential for Error\nArtificial intelligence is an evolving technology that is known to make errors, hallucinations, miscalculations, or provide outdated or unsafe information. The AI driving this App may occasionally generate recommendations that are physically impossible, medically hazardous, counterproductive, or entirely incorrect. You acknowledge that the AI is not a licensed physician, registered dietitian, certified physical therapist, or human professional.\n\n1.3 Informational Purposes Only\nThe content provided by the App is strictly for informational, educational, and motivational purposes. It does not constitute professional medical advice, diagnosis, or treatment. Always seek the advice of your physician, qualified health care provider, or mental health professional with any questions you may have regarding a medical condition, injury, or health objective.',
      ),
      LegalDocumentSection(
        '2. Assumption of Risk',
        '2.1 High-Risk Activities and Tactical Training\nThe App is designed for tactical athletes, military personnel, law enforcement officers, first responders, emergency medical services (EMS) personnel, and general physical fitness users. These activities—including heavy lifting, high-intensity tactical training, conditioning, endurance tasks, and simulated operational stresses—carry inherent, severe, and occasionally fatal risks of physical injury, emotional trauma, property damage, permanent disability, or death.\n\n2.2 Voluntary Participation and Sole Discretion\nYour use of the App, your implementation of any workout routine, diet plan, or tactical strategy suggested by the AI, and your decision to follow any guidance provided is done entirely at your own risk and sole discretion. You are fully responsible for evaluating your own physical readiness, health status, environmental conditions, and operational safety before performing any action suggested by the App.',
      ),
      LegalDocumentSection(
        '3. Release of Liability and Waiver of Claims',
        '3.1 Broad Release\nTo the maximum extent permitted by applicable law (including Canadian federal and provincial laws, as well as international laws), you—on behalf of yourself, your heirs, assigns, executors, and personal representatives—hereby completely release, waive, discharge, and hold harmless APEX TACTICAL PERFORMANCE, its owner(s), developers, operators, directors, employees, contractors, agents, and affiliates (collectively, the "Released Parties") from any and all liability, claims, demands, losses, damages, lawsuits, or expenses of any kind.\n\n3.2 Coverage of Claims\nThis release applies to any and all injuries, illnesses, infections, physical harm, mental anguish, permanent disabilities, or deaths, whether caused by negligence (active or passive) of the Released Parties, technical failure, inaccurate AI generation, software bugs, or otherwise, arising out of or in any way connected with:\n• The use or misuse of the App;\n• Following, attempting to follow, or modifying any instructions, workouts, meal plans, or advice given by the AI;\n• Any technical malfunction, latency, interruption, or erroneous output produced by the App.',
      ),
      LegalDocumentSection(
        '4. Subscriptions, Payments, and No Refund Policy',
        '4.1 Paid Subscription\nThe App operates on a recurring monthly (or periodic) subscription fee basis. By providing your payment details and subscribing, you authorize us to charge your chosen payment method automatically on a recurring basis until you cancel your subscription.\n\n4.2 Payment Does Not Imply Guarantee of Safety or Results\nYou acknowledge that the monthly subscription fee grants you access to the software platform and its AI engine only. The payment of a subscription fee does not create a professional client-trainer, physician-patient, or fiduciary relationship, nor does it shift any burden of safety, liability, or outcome assurance onto the Released Parties. You are paying for software access, not guaranteed physical safety or specific performance results.\n\n4.3 Cancellation and Refunds\nYou may cancel your subscription at any time through your account settings or app store provider. Cancellations will take effect at the end of the current billing cycle. Unless required by applicable local law, all subscription payments are strictly non-refundable, and no credits or partial refunds will be issued for unused portions of a billing cycle.',
      ),
      LegalDocumentSection(
        '5. International Users and Governing Law',
        '5.1 Jurisdiction and Choice of Law\nThis Agreement, and any dispute arising out of or related to it or your use of the App, shall be governed by, construed, and enforced in accordance with the laws of the Province of Ontario and the federal laws of Canada applicable therein, without regard to conflict of law principles.\n\n5.2 Global Access\nThe App may be accessed globally. If you choose to use the App from outside Canada, you do so entirely on your own initiative and are solely responsible for compliance with local laws, to the extent local laws apply. Regardless of your geographic location, you explicitly agree that any legal action or proceeding arising under this Agreement shall be brought exclusively in the courts located in Toronto, Ontario, and you hereby consent to the personal jurisdiction of such courts.',
      ),
      LegalDocumentSection(
        '6. Indemnification',
        'You agree to indemnify, defend, and hold harmless the Released Parties from and against any and all claims, liabilities, damages, losses, costs, expenses, or fees (including reasonable legal fees) arising out of or relating to:\n• Your violation of this Agreement;\n• Your misuse of the App or reliance upon AI recommendations;\n• Any violation of any third-party right or applicable law by you.',
      ),
      LegalDocumentSection(
        '7. Severability and Entire Agreement',
        'If any provision of this Agreement is found to be unlawful, void, or for any reason unenforceable, that provision shall be deemed severable from this Agreement and shall not affect the validity and enforceability of any remaining provisions. This Agreement constitutes the entire agreement between you and the owner regarding the App, superseding any prior agreements.',
      ),
      LegalDocumentSection(
        'Agreement',
        'BY CLICKING "AGREE," DOWNLOADING, OR SUBSCRIBING TO THE APP, YOU CERTIFY THAT YOU HAVE READ THIS ENTIRE DOCUMENT, FULLY UNDERSTAND ITS TERMS, FREEDOM OF CHOICE, AND THAT YOU ARE GIVING UP SUBSTANTIAL LEGAL RIGHTS, INCLUDING THE RIGHT TO SUE.',
      ),
    ],
  );

  static const privacy = LegalDocument(
    title: 'Privacy Policy',
    sections: [
      LegalDocumentSection(
        'APEX TACTICAL PERFORMANCE',
        'Effective Date: 15 September 2026\nLast Updated: 15 September 2026\n\nAPEX TACTICAL PERFORMANCE ("we," "our," or "us") respects your privacy and is committed to protecting your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you download, subscribe to, or use our mobile application and related services (collectively, the "App").\n\nBy accessing or using the App, you agree to the collection and use of information in accordance with this Privacy Policy. If you do not agree with the terms of this Privacy Policy, please do not access or use the App.',
      ),
      LegalDocumentSection(
        '1. Information We Collect',
        'We collect information to provide, maintain, and improve our AI-driven tactical coaching, fitness, and health services. The types of information we collect include:\n\n1.1 Information You Provide Directly to Us\n• Account and Profile Information: When you register for an account, we may collect your name, email address, username, password, age, gender, and contact details.\n• Health, Fitness, and Tactical Data: To provide personalized AI coaching, you may input physical statistics (such as height, weight, body composition), fitness levels, medical history disclosures, injuries, dietary preferences, and tactical occupational details (e.g., military branch, law enforcement agency, first responder role, shift schedules).\n• Communications: Records of your interactions with our customer support team or communications sent through the App.\n\n1.2 Information Collected Automatically\n• Usage and Interaction Data: Information regarding how you interact with the App, including workout logs, queries submitted to the AI coach, feature usage, and session durations.\n• Device and Technical Data: Device identifiers, operating system version, mobile network information, IP address, and unique device tokens.',
      ),
      LegalDocumentSection(
        '2. How We Use Your Information',
        'We use the information we collect for various business and operational purposes, including to:\n• Operate, maintain, and provide the features and functionality of the App;\n• Power the AI engine to generate customized workout plans, nutrition guidance, and health-related responses based on your queries;\n• Process your subscription payments and manage your account;\n• Monitor and analyze trends, usage, and activities to improve user experience and app security;\n• Communicate with you regarding updates, security alerts, administrative notices, and subscription changes.',
      ),
      LegalDocumentSection(
        '3. Sharing of Your Information',
        'We do not sell, rent, or trade your personal health data or identifiable information to third parties. We may share your information only in the following limited circumstances:\n• Service Providers: With third-party vendors, cloud hosting partners, payment processors, and AI model infrastructure providers who perform services on our behalf, strictly bound by confidentiality obligations.\n• Legal and Safety Obligations: If required to do so by law, or in the good faith belief that such action is necessary to comply with legal processes, protect our rights or property, or ensure the safety of our users or the public.\n• Business Transfers: In connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business by another company.',
      ),
      LegalDocumentSection(
        '4. Artificial Intelligence Data Processing',
        'You acknowledge that when you submit queries, fitness details, or health metrics to the App, that data is processed by our third-party artificial intelligence infrastructure to generate responses. While we implement reasonable technical measures to secure data transit, you should never input highly sensitive government-classified information, national security operational details, or full medical diagnostic records into the AI chat interface.',
      ),
      LegalDocumentSection(
        '5. Data Security',
        'We implement commercially reasonable administrative, technical, and physical security measures designed to protect your personal information from unauthorized access, loss, misuse, or alteration. However, no electronic transmission over the internet or information storage technology can be guaranteed to be 100% secure; therefore, we cannot guarantee absolute security.',
      ),
      LegalDocumentSection(
        '6. International Users and Data Transfers',
        'The App is operated from Canada and governed under Canadian law, including the Personal Information Protection and Electronic Documents Act (PIPEDA) and applicable provincial privacy statutes.\n\nIf you access the App from outside Canada (including the European Union, the United States, or elsewhere), please be aware that your information may be transferred to, stored, and processed in Canada or other jurisdictions where our servers or cloud providers are located. By using the App, you consent to the transfer of your information to countries outside your country of residence, which may have different data protection rules.',
      ),
      LegalDocumentSection(
        '7. Your Privacy Rights',
        'Depending on your geographic jurisdiction (such as Canada, the EU under GDPR, or various U.S. states), you may have certain rights regarding your personal information, including:\n• Access and Rectification: The right to request access to or correction of your personal data.\n• Withdrawal of Consent: The right to withdraw your consent to our processing of your data at any time (which may result in the termination of your ability to use the App).\n• Data Deletion: The right to request the deletion of your account and associated personal data, subject to legal retention obligations.\n\nTo exercise any of these rights, please contact us at: westonhall@live.ca',
      ),
      LegalDocumentSection(
        '8. Children’s Privacy',
        'The App is intended strictly for adults, tactical athletes, military personnel, and professionals aged 18 and older (or the age of majority in their jurisdiction). We do not knowingly collect personal information from individuals under the age of 18. If we learn we have collected personal information from a minor, we will delete that information promptly.',
      ),
      LegalDocumentSection(
        '9. Changes to This Privacy Policy',
        'We may update this Privacy Policy from time to time. When we do, we will revise the "Last Updated" date at the top of this policy. We encourage you to review this Privacy Policy periodically to stay informed about how we protect your information.',
      ),
      LegalDocumentSection(
        '10. Contact Us',
        'If you have any questions, concerns, or complaints about this Privacy Policy or our data practices, please contact us at:\n• App Owner: Weston Hall\n• Email: westonhall@live.ca',
      ),
    ],
  );

  static const billing = LegalDocument(
    title: 'Billing, Subscription, and Cancellation Policy',
    sections: [
      LegalDocumentSection(
        'APEX TACTICAL PERFORMANCE',
        'Effective Date: 15 September 2026\nLast Updated: 15 September 2026\n\nThis Billing, Subscription, and Cancellation Policy outlines the financial terms, renewal mechanisms, and consumer rights associated with paid subscriptions for APEX TACTICAL PERFORMANCE (the "App").\n\nBy subscribing to or purchasing any paid tier of the App, you expressly agree to the pricing, billing cadence, and auto-renewal terms outlined below.',
      ),
      LegalDocumentSection(
        '1. Clear Pricing and Billing Terms',
        '1.1 Subscription Fees\n• Cost: The App is offered on a recurring subscription basis at the rate of \$19.99 CAD per month (plus applicable local taxes such as GST/HST where mandated by law).\n• Billing Cycle: Your subscription begins immediately upon successful payment confirmation. You will be billed automatically on a recurring monthly basis on the calendar date corresponding to your initial purchase date (the "Billing Date").\n\n1.2 Automatic Renewal Notice\nYOUR SUBSCRIPTION WILL AUTOMATICALLY RENEW EACH MONTH UNTIL YOU CANCEL IT.\n\nBy completing your purchase, you authorize us (or our designated payment processor / mobile app store) to store your payment method details and automatically charge the then-current monthly subscription fee to your payment method on each recurring Billing Date without further notice to you, unless required by applicable law.',
      ),
      LegalDocumentSection(
        '2. Cancellation Mechanism',
        'You are completely in control of your subscription and may cancel at any time. To avoid being billed for the subsequent monthly billing cycle, you must cancel your subscription at least 24 hours before your next scheduled Billing Date.\n\nHow to Cancel:\n• If purchased through Apple App Store or Google Play Store: You must manage or cancel your subscription directly through your device’s account settings (Apple ID or Google Play Subscriptions menu). We cannot directly cancel store-billed subscriptions for you due to platform restrictions.\n• If purchased directly through our website / web app (Stripe): You can cancel instantly by logging into your account profile inside the App, navigating to Account Settings > Billing > Cancel Subscription, or by submitting a cancellation request directly to our support email.\n\nUpon cancellation, you will retain full access to the App until the remainder of your current paid billing period expires. No further charges will occur.',
      ),
      LegalDocumentSection(
        '3. Refund Policy',
        'Because the App grants immediate digital access to software tools, AI coaching models, and proprietary content:\n• All subscription fees are strictly non-refundable.\n• We do not provide prorated refunds or credits for partially used billing periods, except where explicitly required by applicable provincial or federal consumer protection laws (e.g., mandatory cooling-off periods in specific jurisdictions).',
      ),
      LegalDocumentSection(
        '4. Consumer Support and Contact Information',
        'If you have any questions regarding your billing history, require assistance with your account, or wish to submit a consumer inquiry, you can reach our support team directly using the details below:\n• Customer Support Email: westonhall@live.ca\n• Business Operating Location: Ottawa, Ontario, Canada\n• Response Time: Our team aims to respond to all inquiries within 24 to 48 business hours.',
      ),
    ],
  );
}

class LegalDocumentScreen extends StatelessWidget {
  const LegalDocumentScreen({super.key, required this.document});

  final LegalDocument document;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF1A1D23),
      appBar: AppBar(
        backgroundColor: const Color(0xFF23272D),
        title: Text(
          document.title,
          style: const TextStyle(color: Color(0xFFE5A93B)),
        ),
      ),
      body: SelectionArea(
        child: ListView.separated(
          padding: const EdgeInsets.all(20),
          itemCount: document.sections.length,
          separatorBuilder: (_, _) => const SizedBox(height: 20),
          itemBuilder: (context, index) {
            final section = document.sections[index];
            return Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  section.heading,
                  style: const TextStyle(
                    color: Color(0xFFE5A93B),
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 6),
                Text(
                  section.text,
                  style: const TextStyle(
                    color: Colors.white70,
                    height: 1.5,
                    fontSize: 14,
                  ),
                ),
              ],
            );
          },
        ),
      ),
    );
  }
}
